#https://gist.github.com/dkurzaj/2a899de8cb5ae698919f0a9bbf7685f0

version: '3.6'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    # volumes:
    #    - "./zookeeper/data:/data"
    #    - "./zookeeper/logs:/datalog"
    ports:
      - "2181:2181"
  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:2.12-2.3.0
    restart: on-failure
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "keyword-count:10:1"
    depends_on:
      - zookeeper
  # https://github.com/hleb-albau/kafka-manager-docker
  kafka-manager:
    container_name: kafka-manage
    image: hlebalbau/kafka-manager:2.0.0.2
    restart: on-failure
    depends_on:
      - kafka1
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
      - "9000:9000"